title: AE 353 (Sp25)
description: The course website for Aerospace Control Systems.
theme: just-the-docs

define: &repository_url 'https://github.com/tbretl/ae353-sp25'

github:
  repository_url: *repository_url

aux_links:
  AE 353 on GitHub: *repository_url

math: mathjax

plugins:
  - jekyll-default-layout

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  note:
    title: Note
    color: yellow
  result:
    title: Result
    color: green
  warning:
    title: Warning
    color: red

enable_copy_code_button: true

baseurl: '/ae353-sp23'